import cv2

standard = [cv2.imread('templates/LettersStandard/1.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/2.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/3.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/4.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/5.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/6.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/7.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/8.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/9.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/10.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/11.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/12.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/13.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/14.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/15.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/16.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/LettersStandard/17.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/0.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/1.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/2.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/3.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/4.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/5.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/6.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/7.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/8.bmp', cv2.IMREAD_GRAYSCALE),
            cv2.imread('templates/NumbersStandard/9.bmp', cv2.IMREAD_GRAYSCALE)]

shear_left = [cv2.imread('templates/LettersShearedLeft/1.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/2.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/3.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/4.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/5.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/6.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/7.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/8.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/9.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/10.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/11.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/12.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/13.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/14.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/15.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/16.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/LettersShearedLeft/17.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/0.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/1.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/2.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/3.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/4.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/5.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/6.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/7.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/8.bmp', cv2.IMREAD_GRAYSCALE),
              cv2.imread('templates/NumbersShearedLeft/9.bmp', cv2.IMREAD_GRAYSCALE)]

shear_right = [cv2.imread('templates/LettersShearedRight/1.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/2.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/3.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/4.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/5.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/6.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/7.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/8.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/9.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/10.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/11.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/12.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/13.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/14.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/15.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/16.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/LettersShearedRight/17.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/0.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/1.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/2.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/3.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/4.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/5.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/6.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/7.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/8.bmp', cv2.IMREAD_GRAYSCALE),
               cv2.imread('templates/NumbersShearedRight/9.bmp', cv2.IMREAD_GRAYSCALE)]


def get_templates():
    return [standard, shear_left, shear_right]
